#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_LF = 1,
  anon_sym_DASH_DASH_DASH_LF = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_shorthand_label = 5,
  anon_sym_COLON = 6,
  aux_sym_field_label_token1 = 7,
  sym_barline = 8,
  aux_sym_cluster_token1 = 9,
  sym_embellishment = 10,
  sym_pitch = 11,
  sym_duration = 12,
  sym_connector = 13,
  anon_sym_POUND = 14,
  aux_sym_comment_token1 = 15,
  sym_file = 16,
  sym_tune = 17,
  aux_sym__body = 18,
  sym_voice = 19,
  sym_header = 20,
  sym__header_field = 21,
  sym_field = 22,
  sym__field_parts = 23,
  sym_field_label = 24,
  sym_field_value = 25,
  sym_bar = 26,
  sym__bar_content = 27,
  sym_cluster = 28,
  sym_note = 29,
  sym__blank_line = 30,
  sym_comment = 31,
  sym_tail_comment = 32,
  aux_sym_file_repeat1 = 33,
  aux_sym_file_repeat2 = 34,
  aux_sym_voice_repeat1 = 35,
  aux_sym_header_repeat1 = 36,
  aux_sym_bar_repeat1 = 37,
  aux_sym_cluster_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_DASH_DASH_DASH_LF] = "---\n",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_shorthand_label] = "shorthand_label",
  [anon_sym_COLON] = ":",
  [aux_sym_field_label_token1] = "field_label_token1",
  [sym_barline] = "barline",
  [aux_sym_cluster_token1] = "cluster_token1",
  [sym_embellishment] = "embellishment",
  [sym_pitch] = "pitch",
  [sym_duration] = "duration",
  [sym_connector] = "connector",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_file] = "file",
  [sym_tune] = "tune",
  [aux_sym__body] = "_body",
  [sym_voice] = "voice",
  [sym_header] = "header",
  [sym__header_field] = "_header_field",
  [sym_field] = "field",
  [sym__field_parts] = "_field_parts",
  [sym_field_label] = "field_label",
  [sym_field_value] = "field_value",
  [sym_bar] = "bar",
  [sym__bar_content] = "_bar_content",
  [sym_cluster] = "cluster",
  [sym_note] = "note",
  [sym__blank_line] = "_blank_line",
  [sym_comment] = "comment",
  [sym_tail_comment] = "tail_comment",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym_file_repeat2] = "file_repeat2",
  [aux_sym_voice_repeat1] = "voice_repeat1",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_bar_repeat1] = "bar_repeat1",
  [aux_sym_cluster_repeat1] = "cluster_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DASH_DASH_DASH_LF] = anon_sym_DASH_DASH_DASH_LF,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_shorthand_label] = sym_shorthand_label,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_field_label_token1] = aux_sym_field_label_token1,
  [sym_barline] = sym_barline,
  [aux_sym_cluster_token1] = aux_sym_cluster_token1,
  [sym_embellishment] = sym_embellishment,
  [sym_pitch] = sym_pitch,
  [sym_duration] = sym_duration,
  [sym_connector] = sym_connector,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_file] = sym_file,
  [sym_tune] = sym_tune,
  [aux_sym__body] = aux_sym__body,
  [sym_voice] = sym_voice,
  [sym_header] = sym_header,
  [sym__header_field] = sym__header_field,
  [sym_field] = sym_field,
  [sym__field_parts] = sym__field_parts,
  [sym_field_label] = sym_field_label,
  [sym_field_value] = sym_field_value,
  [sym_bar] = sym_bar,
  [sym__bar_content] = sym__bar_content,
  [sym_cluster] = sym_cluster,
  [sym_note] = sym_note,
  [sym__blank_line] = sym__blank_line,
  [sym_comment] = sym_comment,
  [sym_tail_comment] = sym_tail_comment,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym_file_repeat2] = aux_sym_file_repeat2,
  [aux_sym_voice_repeat1] = aux_sym_voice_repeat1,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_bar_repeat1] = aux_sym_bar_repeat1,
  [aux_sym_cluster_repeat1] = aux_sym_cluster_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_shorthand_label] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_field_label_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_barline] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_cluster_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_embellishment] = {
    .visible = true,
    .named = true,
  },
  [sym_pitch] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_connector] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tune] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__body] = {
    .visible = false,
    .named = false,
  },
  [sym_voice] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym__header_field] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__field_parts] = {
    .visible = false,
    .named = true,
  },
  [sym_field_label] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value] = {
    .visible = true,
    .named = true,
  },
  [sym_bar] = {
    .visible = true,
    .named = true,
  },
  [sym__bar_content] = {
    .visible = false,
    .named = true,
  },
  [sym_cluster] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tail_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_voice_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bar_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cluster_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_field,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__field_parts, 2,
    sym__field_parts,
    sym_field,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '&') ADVANCE(14);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '|') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '_' ||
          lookahead == '~') ADVANCE(25);
      if (lookahead == '+' ||
          lookahead == '.' ||
          lookahead == '/') ADVANCE(24);
      if (('a' <= lookahead && lookahead <= 'h') ||
          lookahead == 'l') ADVANCE(23);
      if (('j' <= lookahead && lookahead <= 'v') ||
          ('x' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\t') SKIP(1)
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '\'' ||
          lookahead == ',' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == '|') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead == '+' ||
          lookahead == '.' ||
          lookahead == '/') ADVANCE(24);
      if (lookahead == '-' ||
          lookahead == '_' ||
          lookahead == '~') ADVANCE(25);
      if (('a' <= lookahead && lookahead <= 'h') ||
          lookahead == 'l') ADVANCE(23);
      if (('j' <= lookahead && lookahead <= 'v') ||
          ('x' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '&') ADVANCE(14);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '|') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8)
      if (('a' <= lookahead && lookahead <= 'h') ||
          lookahead == 'l') ADVANCE(23);
      if (('j' <= lookahead && lookahead <= 'v') ||
          ('x' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH_LF);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_shorthand_label);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '|') ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_field_label_token1);
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '\'' ||
          lookahead == ',' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_field_label_token1);
      if (lookahead == ' ' ||
          lookahead == '\'' ||
          lookahead == ',' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_barline);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_barline);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == '|') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_cluster_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_embellishment);
      if (lookahead == 'j' ||
          lookahead == 'k' ||
          ('m' <= lookahead && lookahead <= 'v') ||
          ('x' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_pitch);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '+' ||
          lookahead == '.' ||
          lookahead == '/') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_connector);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_connector);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 28},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 28},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH_LF] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_shorthand_label] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_barline] = ACTIONS(1),
    [sym_embellishment] = ACTIONS(1),
    [sym_pitch] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_connector] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
  },
  [1] = {
    [sym_file] = STATE(58),
    [sym_tune] = STATE(28),
    [sym_header] = STATE(3),
    [sym__blank_line] = STATE(20),
    [sym_comment] = STATE(20),
    [aux_sym_file_repeat1] = STATE(20),
    [aux_sym_file_repeat2] = STATE(28),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_DASH_DASH_DASH_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
  },
  [2] = {
    [aux_sym__body] = STATE(2),
    [sym_voice] = STATE(2),
    [sym_field] = STATE(11),
    [sym_bar] = STATE(5),
    [sym__bar_content] = STATE(12),
    [sym_cluster] = STATE(12),
    [sym_note] = STATE(29),
    [sym__blank_line] = STATE(2),
    [sym_comment] = STATE(2),
    [aux_sym_voice_repeat1] = STATE(5),
    [aux_sym_bar_repeat1] = STATE(12),
    [aux_sym_cluster_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [anon_sym_DASH_DASH_DASH_LF] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(14),
    [sym_shorthand_label] = ACTIONS(17),
    [sym_barline] = ACTIONS(20),
    [sym_embellishment] = ACTIONS(23),
    [sym_pitch] = ACTIONS(26),
    [anon_sym_POUND] = ACTIONS(29),
  },
  [3] = {
    [aux_sym__body] = STATE(4),
    [sym_voice] = STATE(4),
    [sym_field] = STATE(11),
    [sym_bar] = STATE(5),
    [sym__bar_content] = STATE(12),
    [sym_cluster] = STATE(12),
    [sym_note] = STATE(29),
    [sym__blank_line] = STATE(4),
    [sym_comment] = STATE(4),
    [aux_sym_voice_repeat1] = STATE(5),
    [aux_sym_bar_repeat1] = STATE(12),
    [aux_sym_cluster_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(32),
    [anon_sym_LF] = ACTIONS(34),
    [anon_sym_DASH_DASH_DASH_LF] = ACTIONS(32),
    [anon_sym_LPAREN] = ACTIONS(36),
    [sym_shorthand_label] = ACTIONS(38),
    [sym_barline] = ACTIONS(40),
    [sym_embellishment] = ACTIONS(42),
    [sym_pitch] = ACTIONS(44),
    [anon_sym_POUND] = ACTIONS(7),
  },
  [4] = {
    [aux_sym__body] = STATE(2),
    [sym_voice] = STATE(2),
    [sym_field] = STATE(11),
    [sym_bar] = STATE(5),
    [sym__bar_content] = STATE(12),
    [sym_cluster] = STATE(12),
    [sym_note] = STATE(29),
    [sym__blank_line] = STATE(2),
    [sym_comment] = STATE(2),
    [aux_sym_voice_repeat1] = STATE(5),
    [aux_sym_bar_repeat1] = STATE(12),
    [aux_sym_cluster_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(46),
    [anon_sym_LF] = ACTIONS(48),
    [anon_sym_DASH_DASH_DASH_LF] = ACTIONS(46),
    [anon_sym_LPAREN] = ACTIONS(36),
    [sym_shorthand_label] = ACTIONS(38),
    [sym_barline] = ACTIONS(40),
    [sym_embellishment] = ACTIONS(42),
    [sym_pitch] = ACTIONS(44),
    [anon_sym_POUND] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym_shorthand_label,
    ACTIONS(42), 1,
      sym_embellishment,
    ACTIONS(44), 1,
      sym_pitch,
    ACTIONS(50), 1,
      anon_sym_LF,
    ACTIONS(52), 1,
      sym_barline,
    ACTIONS(54), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_tail_comment,
    STATE(9), 2,
      sym_bar,
      aux_sym_voice_repeat1,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(12), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [39] = 11,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym_shorthand_label,
    ACTIONS(42), 1,
      sym_embellishment,
    ACTIONS(44), 1,
      sym_pitch,
    ACTIONS(52), 1,
      sym_barline,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(56), 1,
      anon_sym_LF,
    STATE(60), 1,
      sym_tail_comment,
    STATE(9), 2,
      sym_bar,
      aux_sym_voice_repeat1,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(12), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [78] = 11,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym_shorthand_label,
    ACTIONS(42), 1,
      sym_embellishment,
    ACTIONS(44), 1,
      sym_pitch,
    ACTIONS(52), 1,
      sym_barline,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(58), 1,
      anon_sym_LF,
    STATE(53), 1,
      sym_tail_comment,
    STATE(9), 2,
      sym_bar,
      aux_sym_voice_repeat1,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(12), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [117] = 9,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym_shorthand_label,
    ACTIONS(42), 1,
      sym_embellishment,
    ACTIONS(44), 1,
      sym_pitch,
    ACTIONS(52), 1,
      sym_barline,
    ACTIONS(60), 2,
      anon_sym_LF,
      anon_sym_POUND,
    STATE(7), 2,
      sym_bar,
      aux_sym_voice_repeat1,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(12), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [151] = 9,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_shorthand_label,
    ACTIONS(70), 1,
      sym_barline,
    ACTIONS(73), 1,
      sym_embellishment,
    ACTIONS(76), 1,
      sym_pitch,
    ACTIONS(62), 2,
      anon_sym_LF,
      anon_sym_POUND,
    STATE(9), 2,
      sym_bar,
      aux_sym_voice_repeat1,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(12), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [185] = 9,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym_shorthand_label,
    ACTIONS(42), 1,
      sym_embellishment,
    ACTIONS(44), 1,
      sym_pitch,
    ACTIONS(52), 1,
      sym_barline,
    ACTIONS(60), 2,
      anon_sym_LF,
      anon_sym_POUND,
    STATE(6), 2,
      sym_bar,
      aux_sym_voice_repeat1,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(12), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [219] = 8,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym_shorthand_label,
    ACTIONS(42), 1,
      sym_embellishment,
    ACTIONS(44), 1,
      sym_pitch,
    ACTIONS(79), 1,
      sym_barline,
    STATE(7), 2,
      sym_bar,
      aux_sym_voice_repeat1,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(12), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [249] = 7,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym_shorthand_label,
    ACTIONS(42), 1,
      sym_embellishment,
    ACTIONS(44), 1,
      sym_pitch,
    ACTIONS(81), 1,
      sym_barline,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(13), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [275] = 7,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 1,
      sym_shorthand_label,
    ACTIONS(89), 1,
      sym_barline,
    ACTIONS(91), 1,
      sym_embellishment,
    ACTIONS(94), 1,
      sym_pitch,
    STATE(29), 2,
      sym_note,
      aux_sym_cluster_repeat1,
    STATE(13), 4,
      sym_field,
      sym__bar_content,
      sym_cluster,
      aux_sym_bar_repeat1,
  [301] = 1,
    ACTIONS(97), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH_DASH_DASH_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [313] = 1,
    ACTIONS(99), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH_DASH_DASH_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [325] = 1,
    ACTIONS(101), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH_DASH_DASH_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [337] = 1,
    ACTIONS(103), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH_DASH_DASH_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [349] = 1,
    ACTIONS(105), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH_DASH_DASH_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [361] = 1,
    ACTIONS(107), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH_DASH_DASH_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [373] = 6,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH_DASH_LF,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(109), 1,
      anon_sym_LF,
    STATE(3), 1,
      sym_header,
    STATE(30), 2,
      sym_tune,
      aux_sym_file_repeat2,
    STATE(25), 3,
      sym__blank_line,
      sym_comment,
      aux_sym_file_repeat1,
  [395] = 1,
    ACTIONS(111), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DASH_DASH_DASH_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [407] = 1,
    ACTIONS(60), 7,
      anon_sym_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [417] = 1,
    ACTIONS(113), 7,
      anon_sym_LF,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
      anon_sym_POUND,
  [427] = 6,
    ACTIONS(115), 1,
      anon_sym_DASH_DASH_DASH_LF,
    ACTIONS(117), 1,
      aux_sym_field_label_token1,
    STATE(24), 1,
      aux_sym_header_repeat1,
    STATE(43), 1,
      sym_field_label,
    STATE(51), 1,
      sym__header_field,
    STATE(54), 1,
      sym__field_parts,
  [446] = 4,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(123), 1,
      anon_sym_DASH_DASH_DASH_LF,
    ACTIONS(125), 1,
      anon_sym_POUND,
    STATE(25), 3,
      sym__blank_line,
      sym_comment,
      aux_sym_file_repeat1,
  [461] = 6,
    ACTIONS(128), 1,
      anon_sym_DASH_DASH_DASH_LF,
    ACTIONS(130), 1,
      aux_sym_field_label_token1,
    STATE(27), 1,
      aux_sym_header_repeat1,
    STATE(43), 1,
      sym_field_label,
    STATE(51), 1,
      sym__header_field,
    STATE(54), 1,
      sym__field_parts,
  [480] = 6,
    ACTIONS(130), 1,
      aux_sym_field_label_token1,
    ACTIONS(132), 1,
      anon_sym_DASH_DASH_DASH_LF,
    STATE(24), 1,
      aux_sym_header_repeat1,
    STATE(43), 1,
      sym_field_label,
    STATE(51), 1,
      sym__header_field,
    STATE(54), 1,
      sym__field_parts,
  [499] = 4,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH_DASH_LF,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_header,
    STATE(31), 2,
      sym_tune,
      aux_sym_file_repeat2,
  [513] = 4,
    ACTIONS(136), 1,
      aux_sym_cluster_token1,
    ACTIONS(138), 1,
      sym_embellishment,
    ACTIONS(140), 1,
      sym_pitch,
    STATE(32), 2,
      sym_note,
      aux_sym_cluster_repeat1,
  [527] = 4,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH_DASH_LF,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_header,
    STATE(31), 2,
      sym_tune,
      aux_sym_file_repeat2,
  [541] = 4,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 1,
      anon_sym_DASH_DASH_DASH_LF,
    STATE(3), 1,
      sym_header,
    STATE(31), 2,
      sym_tune,
      aux_sym_file_repeat2,
  [555] = 4,
    ACTIONS(149), 1,
      aux_sym_cluster_token1,
    ACTIONS(151), 1,
      sym_embellishment,
    ACTIONS(154), 1,
      sym_pitch,
    STATE(32), 2,
      sym_note,
      aux_sym_cluster_repeat1,
  [569] = 1,
    ACTIONS(157), 5,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
  [577] = 1,
    ACTIONS(159), 5,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
  [585] = 4,
    ACTIONS(161), 1,
      aux_sym_cluster_token1,
    ACTIONS(165), 1,
      sym_duration,
    ACTIONS(167), 1,
      sym_connector,
    ACTIONS(163), 2,
      sym_embellishment,
      sym_pitch,
  [599] = 1,
    ACTIONS(169), 5,
      anon_sym_LPAREN,
      sym_shorthand_label,
      sym_barline,
      sym_embellishment,
      sym_pitch,
  [607] = 4,
    ACTIONS(171), 1,
      aux_sym_cluster_token1,
    ACTIONS(175), 1,
      sym_duration,
    ACTIONS(177), 1,
      sym_connector,
    ACTIONS(173), 2,
      sym_embellishment,
      sym_pitch,
  [621] = 3,
    ACTIONS(179), 1,
      aux_sym_cluster_token1,
    ACTIONS(183), 1,
      sym_connector,
    ACTIONS(181), 2,
      sym_embellishment,
      sym_pitch,
  [632] = 3,
    ACTIONS(171), 1,
      aux_sym_cluster_token1,
    ACTIONS(177), 1,
      sym_connector,
    ACTIONS(173), 2,
      sym_embellishment,
      sym_pitch,
  [643] = 3,
    ACTIONS(130), 1,
      aux_sym_field_label_token1,
    STATE(43), 1,
      sym_field_label,
    STATE(52), 1,
      sym__field_parts,
  [653] = 2,
    ACTIONS(171), 1,
      aux_sym_cluster_token1,
    ACTIONS(173), 2,
      sym_embellishment,
      sym_pitch,
  [661] = 2,
    ACTIONS(179), 1,
      aux_sym_cluster_token1,
    ACTIONS(181), 2,
      sym_embellishment,
      sym_pitch,
  [669] = 2,
    ACTIONS(187), 1,
      anon_sym_COLON,
    ACTIONS(185), 2,
      anon_sym_LF,
      anon_sym_RPAREN,
  [677] = 1,
    ACTIONS(189), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COLON,
  [683] = 2,
    ACTIONS(191), 1,
      aux_sym_cluster_token1,
    ACTIONS(193), 2,
      sym_embellishment,
      sym_pitch,
  [691] = 2,
    ACTIONS(115), 1,
      anon_sym_DASH_DASH_DASH_LF,
    ACTIONS(195), 1,
      aux_sym_field_label_token1,
  [698] = 2,
    ACTIONS(197), 1,
      aux_sym_field_label_token1,
    STATE(49), 1,
      sym_field_value,
  [705] = 1,
    ACTIONS(199), 2,
      anon_sym_LF,
      anon_sym_RPAREN,
  [710] = 1,
    ACTIONS(201), 2,
      anon_sym_LF,
      anon_sym_RPAREN,
  [715] = 1,
    ACTIONS(203), 1,
      sym_pitch,
  [719] = 1,
    ACTIONS(205), 1,
      anon_sym_LF,
  [723] = 1,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
  [727] = 1,
    ACTIONS(56), 1,
      anon_sym_LF,
  [731] = 1,
    ACTIONS(209), 1,
      anon_sym_LF,
  [735] = 1,
    ACTIONS(58), 1,
      anon_sym_LF,
  [739] = 1,
    ACTIONS(211), 1,
      aux_sym_comment_token1,
  [743] = 1,
    ACTIONS(213), 1,
      anon_sym_LF,
  [747] = 1,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
  [751] = 1,
    ACTIONS(217), 1,
      anon_sym_LF,
  [755] = 1,
    ACTIONS(219), 1,
      anon_sym_LF,
  [759] = 1,
    ACTIONS(221), 1,
      aux_sym_comment_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 39,
  [SMALL_STATE(7)] = 78,
  [SMALL_STATE(8)] = 117,
  [SMALL_STATE(9)] = 151,
  [SMALL_STATE(10)] = 185,
  [SMALL_STATE(11)] = 219,
  [SMALL_STATE(12)] = 249,
  [SMALL_STATE(13)] = 275,
  [SMALL_STATE(14)] = 301,
  [SMALL_STATE(15)] = 313,
  [SMALL_STATE(16)] = 325,
  [SMALL_STATE(17)] = 337,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 361,
  [SMALL_STATE(20)] = 373,
  [SMALL_STATE(21)] = 395,
  [SMALL_STATE(22)] = 407,
  [SMALL_STATE(23)] = 417,
  [SMALL_STATE(24)] = 427,
  [SMALL_STATE(25)] = 446,
  [SMALL_STATE(26)] = 461,
  [SMALL_STATE(27)] = 480,
  [SMALL_STATE(28)] = 499,
  [SMALL_STATE(29)] = 513,
  [SMALL_STATE(30)] = 527,
  [SMALL_STATE(31)] = 541,
  [SMALL_STATE(32)] = 555,
  [SMALL_STATE(33)] = 569,
  [SMALL_STATE(34)] = 577,
  [SMALL_STATE(35)] = 585,
  [SMALL_STATE(36)] = 599,
  [SMALL_STATE(37)] = 607,
  [SMALL_STATE(38)] = 621,
  [SMALL_STATE(39)] = 632,
  [SMALL_STATE(40)] = 643,
  [SMALL_STATE(41)] = 653,
  [SMALL_STATE(42)] = 661,
  [SMALL_STATE(43)] = 669,
  [SMALL_STATE(44)] = 677,
  [SMALL_STATE(45)] = 683,
  [SMALL_STATE(46)] = 691,
  [SMALL_STATE(47)] = 698,
  [SMALL_STATE(48)] = 705,
  [SMALL_STATE(49)] = 710,
  [SMALL_STATE(50)] = 715,
  [SMALL_STATE(51)] = 719,
  [SMALL_STATE(52)] = 723,
  [SMALL_STATE(53)] = 727,
  [SMALL_STATE(54)] = 731,
  [SMALL_STATE(55)] = 735,
  [SMALL_STATE(56)] = 739,
  [SMALL_STATE(57)] = 743,
  [SMALL_STATE(58)] = 747,
  [SMALL_STATE(59)] = 751,
  [SMALL_STATE(60)] = 755,
  [SMALL_STATE(61)] = 759,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__body, 2),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2), SHIFT_REPEAT(2),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2), SHIFT_REPEAT(40),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2), SHIFT_REPEAT(36),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2), SHIFT_REPEAT(8),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2), SHIFT_REPEAT(50),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2), SHIFT_REPEAT(35),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2), SHIFT_REPEAT(61),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tune, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tune, 2),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bar, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_voice_repeat1, 2),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_voice_repeat1, 2), SHIFT_REPEAT(40),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_voice_repeat1, 2), SHIFT_REPEAT(36),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_voice_repeat1, 2), SHIFT_REPEAT(22),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_voice_repeat1, 2), SHIFT_REPEAT(50),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_voice_repeat1, 2), SHIFT_REPEAT(35),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bar_repeat1, 2), SHIFT_REPEAT(40),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bar_repeat1, 2), SHIFT_REPEAT(36),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bar_repeat1, 2),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bar_repeat1, 2), SHIFT_REPEAT(50),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bar_repeat1, 2), SHIFT_REPEAT(35),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voice, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voice, 5),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voice, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voice, 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bar, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2), SHIFT_REPEAT(44),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2), SHIFT_REPEAT(25),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2), SHIFT_REPEAT(61),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat2, 2),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat2, 2), SHIFT_REPEAT(26),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cluster_repeat1, 2),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cluster_repeat1, 2), SHIFT_REPEAT(50),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cluster_repeat1, 2), SHIFT_REPEAT(35),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cluster, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 1),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note, 1),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 3),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note, 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_parts, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_label, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 4),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note, 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_value, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_parts, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__header_field, 1, .production_id = 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tail_comment, 2),
  [215] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_BagNotation(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
